[project]
name = "discordbot"
version = "0.1.0"
description = "A Discord bot integrating MCP tools for automated moderation and Reddit interactions."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=3.13.0",
    "mcp[cli]>=1.16.0",
]
